dist: xenial
language: node_js
sudo: false

node_js:
  - "12.12"

branches:
  only:
    - master
    - /next\/.*/

jobs:
  include:
    - name: Build
      script: npm run build
    - name: Test
      script:
        - npm test -- --ci --coverage
        - sh .travis/check-strict-null-errors.sh

env:
  global:
    - APP_MOUNT_URI="/"
    - API_URI="/graphql/"

after_success:
  - codecov
