name: Create-check
description: "Creates check for PR"
inputs:
  CHECK_ID:
    description: "Check id"
    required: true
  CHECK_NAME:
    description: "Name of check - must be the same here and in create check"
    required: true
  STATUS:
    description: "Status of check"
    required: true
  CONCLUSION:
    description: "Conclusion of check, required if status completed"
    required: false
  TITLE: 
    description: "Title of check"
    required: true
  SUMMARY:
    description: "Summary of check"
    required: true
  DETAILS_URL:
    description: "Url with details to check"
    required: true

runs:
  using: composite
  steps:
    - name: Update check
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        CHECK_ID: ${{ inputs.CHECK_ID }}
        NAME: ${{ inputs.CHECK_NAME }}
        STATUS: ${{ inputs.STATUS }}
        CONCLUSION: '"conclusion":"${{inputs.CONCLUSION}}",'
        TITLE: ${{ inputs.TITLE }}
        SUMMARY: ${{ inputs.SUMMARY }}
        DETAILS_URL: ${{ inputs.DETAILS_URL }}
      run: |
        curl -L \
        -X PATCH \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ env.GH_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/saleor/saleor-dashboard/check-runs/${{env.CHECK_ID}} \
        -d '{
          "name":"${{env.NAME}}",
          "status":"${{env.STATUS}}",
          ${{ env.CONCLUSION }}
          "output":{
            "title":"${{ env.TITLE }}",
            "summary":"${{ env.SUMMARY }}",
            "text":"",
            "details_url":"${{ env.DETAILS_URL }}"
          }
        }'