name: Create check
on:
  push:

jobs:
  add-check-to-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: create-check
        uses: ./.github/actions/checks/create-pull-request-check
        with:
          PR_HEAD: "Test-add-tests-check-to-release-PR"
          CHECK_NAME: "Automation_tests_run"
          STATUS: "in_progress"
          TITLE: "Automation tests run"

      - name: Print PR HEAD_SHA
        run: echo "&{{ steps.create-check.outputs.PR_EXIST }}"

      - id: update-check
        if: ${{ steps.create-check.outputs.PR_EXIST }}
        uses: ./.github/actions/checks/update-pull-request-check
        with:
          CHECK_ID: ${{ steps.create-check.outputs.CHECK_ID }}
          CHECK_NAME: "Automation_tests_run"
          STATUS: "completed"
          CONCLUSION: "success"
          TITLE: "Automation tests run"
          SUMMARY: "There are 0 failures, 2 warnings, and 1 notices."
          DETAILS_URL: ""

        # env:
        #   GH_TOKEN: ${{ github.token }}
        #   CHECK_ID: ${{ steps.create-check.outputs.CHECK_ID }}
        # run: |
        #   curl -L \
        #   -X PATCH \
        #   -H "Accept: application/vnd.github+json" \
        #   -H "Authorization: Bearer ${{ env.GH_TOKEN }}" \
        #   -H "X-GitHub-Api-Version: 2022-11-28" \
        #   https://api.github.com/repos/saleor/saleor-dashboard/check-runs/${{env.CHECK_ID}} \
        #   -d '{
        #     "name":"Automation_tests_run",
        #     "status":"completed",
        #     "conclusion":"success",
        #     "output":{
        #       "title":"Automation tests run",
        #       "summary":"There are 0 failures, 2 warnings, and 1 notices.",
        #       "text":""
        #     }
        #   }'