name: Pull Request Action
on:
  push:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }} # Expose the token for GH CLI
        run: |
          export GITHUB_TOKEN=$( \
            curl --request GET --url ${{ secrets.VAULT_URL}} --header "Authorization: JWT ${{ secrets.VAULT_JWT }}" | jq -r .token \
          )
          
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/saleor/saleor-dashboard/pulls \
          -f title='Pr created b' \
          -f body='Please pull these awesome changes in!' \
          -f head='Test-add-tests-check-to-release-PR' \
          -f base='main' 