name: MacawUI migration
on: [push]

jobs:
  current_state:
    runs-on: ubuntu-latest
    name: "Calculate current state"
    outputs: 
      main_statistics: ${{ steps.store_import_stats.outputs.MAIN_STATISTICS }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-qa-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-qa-${{ env.cache-name }}-
            ${{ runner.os }}-qa-
            ${{ runner.os }}-

      - name: Install deps
        run: |
          npm ci
      - name: Store import stats
        id: store_import_stats
        run: |
          stats=$(npm run dep-status -- --output-type json | tail -n +5 | jq ".summary.info")
          echo "Statistics on main branch: ${stats}"
          echo "MAIN_STATISTICS=${stats}" >> $GITHUB_OUTPUT

  check_migation_status:
    runs-on: ubuntu-latest
    name: "Migration check"
    needs: current_state
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-qa-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-qa-${{ env.cache-name }}-
            ${{ runner.os }}-qa-
            ${{ runner.os }}-

      - name: Install deps
        run: |
          npm ci
      - name: "Calculate stats"
        env:
          latest: ${{ needs.current_state.outputs.main_statistics }}
        run: |
          current=$(npm run dep-status -- --output-type json | tail -n +5 | jq ".summary.info")
          echo Imports in main: $latest
          echo Incomming imports: $current
          echo Difference: $(latest - current)