name: Cypress nightly tests
on:
  schedule:
  - cron: '00 02 * * *'
    
jobs:
  nightly:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress nightly tests 🌃
        uses: cypress-io/github-action@v2
        env:
          API_URI: https://qa.staging.saleor.cloud/graphql/
          APP_MOUNT_URI: ${{ secrets.APP_MOUNT_URI }}
          CYPRESS_USER_NAME: ${{ secrets.CYPRESS_USER_NAME }}
          CYPRESS_SECOND_USER_NAME: ${{ secrets.CYPRESS_SECOND_USER_NAME }}
          CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
          CYPRESS_PERMISSIONS_USERS_PASSWORD: ${{ secrets.CYPRESS_PERMISSIONS_USERS_PASSWORD }}
          CYPRESS_MAILHOG: ${{ secrets.CYPRESS_MAILHOG }}
        with:
          command: npm run cy:run:qa
      - uses: actions/upload-artifact@v1
        if: ${{ failure() }}
        with:
          name: cypress-videos
          path: cypress/videos

