name: E2E

on:
  pull_request:
    types: [edited]

jobs:

  test1: 
    runs-on: ubuntu-latest
    steps:

      - name: Get containers
        id: get_containers
        uses: actions/github-script@v6
        env:
          pull_request_body: ${{ github.event.pull_request.body }}
        with:
          script: |
                  const containers = [];
                  try{
                    const numberOfContainersRegex = /CONTAINERS=(\d*)/
                    const numberOfContainers = pullRequestBody.match(numberOfContainersRegex);
                    for(let i=1; i<=numberOfContainers[1]; i++){
                      containers.push(i)
                    }
                  }catch{
                    containers.push(5)
                  }
                  return {containers: containers}
        
      - name: echo
        run: |
              echo ${{ steps.get_containers.outputs.result }}

  test2:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        {
        containers: [1,2,3]
        }
    steps:
      - name: echo
        run: |
              echo cont